/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Drivers: typeof import('./src/components/Drivers.vue')['default']
    EmbeddedPdf: typeof import('./src/components/EmbeddedPdf.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HistoryGraph: typeof import('./src/components/HistoryGraph.vue')['default']
    MenuViewer: typeof import('./src/components/MenuViewer.vue')['default']
    Message: typeof import('./src/components/Message.vue')['default']
    Messages: typeof import('./src/components/Messages.vue')['default']
    ReportSlide: typeof import('./src/components/ReportSlide.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slide: typeof import('./src/components/Slide.vue')['default']
    TestComponent: typeof import('./src/components/TestComponent.vue')['default']
  }
}
